# Generated by Django 4.1.7 on 2023-03-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
