# Generated by Django 4.1.7 on 2023-03-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_patientemail_appointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
