# Generated by Django 4.1.7 on 2023-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
