# Generated by Django 4.1.7 on 2023-03-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Dname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
